/**
 * Generates styles.css from src/styles.src.css.
 *
 * Column widths are driven by one CSS custom property per column index (§8.5/1), which needs a
 * matching static rule per index. Hand-maintaining 128 of those is a bad idea, and injecting a
 * <style> element at runtime is forbidden (`no-forbidden-elements`), so the rules are generated
 * at build time into the release artefact.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = readFileSync(join(root, "src/styles.src.css"), "utf8");

const constants = readFileSync(join(root, "src/view/constants.ts"), "utf8");
const match = /export const MAX_COLS = (\d+);/.exec(constants);
if (!match) {
	throw new Error("MAX_COLS not found in src/view/constants.ts");
}
const maxCols = Number.parseInt(match[1], 10);

const rules = [];
for (let c = 0; c < maxCols; c++) {
	rules.push(
		`.mds-cell[data-col="${c}"],.mds-colhead[data-col="${c}"]{width:var(--mds-col-${c},var(--mds-col-default));min-width:var(--mds-col-${c},var(--mds-col-default))}`,
	);
}

const banner = `/* Generated by scripts/gen-styles.mjs from src/styles.src.css. Do not edit directly. */\n`;
const generated = `\n/* ---- generated: per-column widths, ${maxCols} columns (see scripts/gen-styles.mjs) ---- */\n${rules.join("\n")}\n`;

writeFileSync(join(root, "styles.css"), banner + source.trimEnd() + "\n" + generated, "utf8");
process.stdout.write(`styles.css written (${maxCols} column rules)\n`);
